# Generated by Django 5.2.8 on 2026-01-03 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_order_phoned_delivered_order_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('burmese_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('image1', models.ImageField(upload_to='special/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='special/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='special/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.dish')),
            ],
        ),
    ]
