# Generated by Django 5.2.8 on 2026-01-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdish',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
